#!/usr/bin/env python3
"""Split the monolithic music vocabulary into a TBox file and an ABox file.

Why: the graph is destined for a triplestore where the model (TBox) and the
instance catalogue (ABox) live in separate named graphs. Physically separating
the source files is the git-friendly half of that — a loader assigns each file
to its graph at ingest (see scripts/load_graphs.py).

How: the two layers are *interleaved* in the source (e.g. genres are ABox
individuals sitting inside the "CLASSES — GENRES" section), so a line-range cut
would corrupt the split. Instead we classify each subject *by identity* using
rdflib — a subject typed with an OWL/RDFS metaclass (owl:Class, owl:*Property,
owl:Ontology, …) is TBox; every other subject is an ABox individual — then route
the original, verbatim text block (comments, banners, inline provenance notes and
all) to the matching output. Nothing is written until an in-memory round-trip
proves the two outputs partition the original triples exactly.

Safe to re-run: the TBox file is the source *and* an output, so once split it
holds no ABox subjects. The script detects that case and exits without writing,
rather than overwriting music_catalog_data.ttl with an empty file.
"""
from __future__ import annotations

import sys
from pathlib import Path

from rdflib import Graph, RDF, RDFS, OWL, URIRef, BNode
from rdflib.compare import isomorphic

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "ontology" / "music_vocabulary_comprehensive.ttl"
TBOX_OUT = ROOT / "ontology" / "music_vocabulary_comprehensive.ttl"  # rewritten in place
ABOX_OUT = ROOT / "ontology" / "music_catalog_data.ttl"

# A subject is TBox iff it is asserted to be one of these metaclasses.
METACLASSES = {
    OWL.Class, OWL.ObjectProperty, OWL.DatatypeProperty, OWL.AnnotationProperty,
    OWL.TransitiveProperty, OWL.SymmetricProperty, OWL.FunctionalProperty,
    OWL.InverseFunctionalProperty, OWL.Ontology, RDFS.Class, RDF.Property,
}

TBOX_BANNER = (
    "###############################################################################\n"
    "# MUSIC VOCABULARY — TBOX (model: classes, properties, ontology header)\n"
    "#\n"
    "# Generated by scripts/split_tbox_abox.py. Instance data (the ABox) lives in\n"
    "# music_catalog_data.ttl. At triplestore ingest this file is loaded into the\n"
    "# named graph <https://www.somusicvocabulary.org/music/tbox>.\n"
    "###############################################################################\n"
)
ABOX_BANNER = (
    "###############################################################################\n"
    "# MUSIC VOCABULARY — ABOX (instance catalogue)\n"
    "#\n"
    "# Generated by scripts/split_tbox_abox.py from the model in\n"
    "# music_vocabulary_comprehensive.ttl. At triplestore ingest this file is loaded\n"
    "# into the named graph <https://www.somusicvocabulary.org/music/abox>.\n"
    "###############################################################################\n"
)


def resolve_subject(token: str, prefixes: dict[str, str]) -> URIRef | None:
    """Resolve the leading token of a statement block to a full IRI."""
    if token.startswith("<") and token.endswith(">"):
        return URIRef(token[1:-1])
    if ":" in token:
        pfx, local = token.split(":", 1)
        base = prefixes.get(pfx)
        if base is None:
            return None
        return URIRef(base + local)
    return None


def main() -> int:
    text = SRC.read_text()

    g = Graph()
    g.parse(data=text, format="turtle")
    prefixes = {p: str(n) for p, n in g.namespaces()}

    # Authoritative TBox subject set: subjects typed with a metaclass.
    tbox_subjects = {
        s for s, o in g.subject_objects(RDF.type) if o in METACLASSES
    }

    # --- Split raw text into blank-line-delimited paragraphs (preserves formatting). ---
    paragraphs: list[list[str]] = []
    cur: list[str] = []
    for ln in text.splitlines():
        if ln.strip() == "":
            if cur:
                paragraphs.append(cur)
                cur = []
        else:
            cur.append(ln)
    if cur:
        paragraphs.append(cur)

    def is_comment_only(p: list[str]) -> bool:
        return all(ln.lstrip().startswith("#") for ln in p)

    def is_prefix(p: list[str]) -> bool:
        first = p[0].lstrip()
        return first.startswith("@prefix") or first.startswith("@base")

    def subject_of(p: list[str]) -> URIRef | None:
        for ln in p:
            if ln.lstrip().startswith("#"):
                continue
            token = ln.split(None, 1)[0]
            return resolve_subject(token, prefixes)
        return None

    prefix_lines: list[str] = []
    tbox_paras: list[list[str]] = []
    abox_paras: list[list[str]] = []
    pending_comments: list[list[str]] = []  # banners awaiting their statement block

    for p in paragraphs:
        if is_prefix(p):
            prefix_lines.extend(p)
            continue
        if is_comment_only(p):
            pending_comments.append(p)
            continue
        subj = subject_of(p)
        dest = tbox_paras if (subj is not None and subj in tbox_subjects) else abox_paras
        dest.extend(pending_comments)
        pending_comments = []
        dest.append(p)
    # Any trailing comments (rare) stay with the data file.
    abox_paras.extend(pending_comments)

    # Guard: the TBox file is both source and output. If it holds no ABox subjects,
    # the split has already run — do NOT write, or we would clobber the existing
    # catalogue file with an empty one.
    if not abox_paras:
        print("Nothing to split: the source contains no ABox subjects "
              "(already split?). No files written.")
        return 0

    header = "\n".join(prefix_lines) + "\n"

    def render(banner: str, paras: list[list[str]]) -> str:
        body = "\n\n".join("\n".join(p) for p in paras)
        return f"{banner}\n{header}\n{body}\n"

    tbox_text = render(TBOX_BANNER, tbox_paras)
    abox_text = render(ABOX_BANNER, abox_paras)

    # --- Verify BEFORE writing: the split must partition the triples exactly. ---
    gt = Graph()
    gt.parse(data=tbox_text, format="turtle")
    ga = Graph()
    ga.parse(data=abox_text, format="turtle")

    # Ground (blank-node-free) triples can be set-compared directly; blank-node
    # triples can't (fresh IDs per parse), so the union is checked by isomorphism.
    def ground(graph: Graph) -> set:
        return {t for t in graph if not any(isinstance(x, BNode) for x in t)}

    errors = []
    ground_t, ground_a = ground(gt), ground(ga)
    if not ground_t.isdisjoint(ground_a):
        errors.append(f"{len(ground_t & ground_a)} ground triples appear in BOTH files (should be disjoint).")
    if not isomorphic(gt + ga, g):
        errors.append(
            f"union not isomorphic to original (TBox {len(gt)} + ABox {len(ga)} vs {len(g)} triples)."
        )
    leaked = [s for s, o in ga.subject_objects(RDF.type) if o in METACLASSES]
    if leaked:
        errors.append(f"{len(leaked)} metaclass-typed subject(s) leaked into the ABox, e.g. {leaked[:3]}.")

    if errors:
        print("SPLIT ABORTED — verification failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    TBOX_OUT.write_text(tbox_text)
    ABOX_OUT.write_text(abox_text)

    print("Split OK (triples preserved, subjects disjoint, no metaclass leak):")
    print(f"  TBox -> {TBOX_OUT.relative_to(ROOT)}: {len(gt)} triples, {len(tbox_paras)} blocks")
    print(f"  ABox -> {ABOX_OUT.relative_to(ROOT)}: {len(ga)} triples, {len(abox_paras)} blocks")
    print(f"  original: {len(g)} triples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
